"""Every word the two settings surfaces put on screen, in one table.

The standalone Windows window and the Codex panel show the same product. Until v0.5.6
they each carried their own English literals - one set in C#, one set in JavaScript - and
the plugin layer had a third set in Python for its own messages. Three copies of the same
vocabulary is how "Retry timing" becomes three different words, and it is why the two
settings surfaces were English no matter what language the rest of the product spoke.

So there is one catalog, here, and both surfaces are handed the resolved language's
strings rather than choosing for themselves:

    messages.language()          decides once, from the Windows preferred UI languages
        |
        +-- controlcli `strings` -> the standalone window, over the bridge it already uses
        +-- mcpui.settings_page  -> the Codex panel, embedded in the page it already seeds

Neither surface guesses. The C# window does not read the registry and the panel's
JavaScript does not look at `navigator.language`, because a product that speaks Korean in
its notifications and English in its settings window is worse than one that picks either.

Keys are stable identifiers and every key exists in every language; `tests/test_locale.py`
asserts that, so a missing string cannot reach a user as a blank label or an English word
in the middle of a Korean sentence.

Brand names are not translated: Codex, Codex Auto Resume, Windows, MCP. Korean particles
attach to them normally.
"""
from __future__ import annotations

from . import messages

# Ordinary UI vocabulary. The `field.*` keys are the settings schema's own names, so a
# setting added to `settings.py` needs a line here and nowhere else; a missing one shows
# the humanised English name rather than a blank, and the test says so out loud.
STRINGS = {
    "en": {
        # Cards.
        "group.recovery": "Automatic recovery",
        "group.limits": "Limits",
        "group.notifications": "Notifications",
        "group.windows": "Windows",

        # Settings, keyed by their schema name.
        "field.recover_usage_limit": "Usage limits",
        "field.recover_network_transient": "Network failures",
        "field.recover_timeout": "Timeouts",
        "field.recover_rate_limit_transient": "Temporary rate limits",
        "field.recover_server_5xx": "Server errors",
        "field.recover_stream_interrupted": "Stream interruptions",
        "field.notifications": "Show notifications",
        "field.notify_interruption": "Interruption detected",
        "field.notify_starting": "Recovery starting",
        "field.notify_result": "Recovery result",
        "field.notify_stopped": "Stopped or out of attempts",
        "field.max_recovery_attempts": "Attempts per interruption",
        "field.max_no_progress": "Stop after no progress",
        "field.max_chain_continuations": "Continuations per task",
        "field.retry_timing": "Retry timing",
        "field.detection_lookback_hours": "Look back",
        "field.startup": "Run at Windows sign-in",

        # Retry timing. The stored value stays English; only the label is translated.
        "choice.conservative": "conservative",
        "choice.normal": "normal",
        "choice.aggressive": "aggressive",

        # The status line, which is the reason either surface gets opened.
        "status.watching": "Watching for interruptions",
        "status.not_running": "Watcher not running",
        "status.unknown": "Watcher status unknown",
        "status.paused": "Watching paused",
        "status.recovery_on": "Automatic recovery is on",
        "status.recovery_paused": "Automatic recovery is paused",
        "status.recovery_idle": "Nothing will be recovered until it is running",
        "status.pending_none": "Nothing pending",
        "status.pending_one": "1 recovery pending",
        "status.pending_many": "{n} recoveries pending",
        "status.unavailable": "Status unavailable",
        "status.unavailable_detail": "Settings can still be changed and saved",

        # Actions.
        "action.save": "Save",
        "action.close": "Close",
        "action.restore": "Restore defaults",
        "action.start": "Start watcher",
        "action.pause": "Pause recovery",
        "action.resume": "Resume recovery",

        # Starting the watcher, and the four things that can come of it.
        "start.working": "Starting the watcher...",
        "start.waiting": "Waiting for it to report in",
        "start.exited": "It started and stopped again - see the logs in the installation folder",
        "start.unconfirmed": "Started, but not confirmed running yet",
        "start.failed": "Could not start the watcher.",

        # The panel's pending table.
        "panel.pending_title": "Waiting to resume",
        "panel.col_conversation": "Conversation",
        "panel.col_state": "State",
        "panel.col_attempts": "Attempts",
        "panel.more": "and {n} more",
        "panel.saving": "Saving...",
        "panel.saved": "Saved.",
        "panel.not_saved": "Not saved: {reason}",
        "panel.refused": "refused",
        "panel.readonly": "Read-only here. Use the Codex Auto Resume settings window to change these.",
        "panel.unavailable": "Settings are not available in this view.",
        "panel.starting": "Starting...",
        "panel.start_failed": "Could not start it: {reason}",
        "panel.start_exited": "It started and stopped again; nothing is watching.",
        "panel.start_unconfirmed": "Started, but not confirmed running yet. Ask for the status again.",

        # What a queued recovery is waiting for. Shown as a pill, so they stay short.
        "state.waiting_reset": "waiting reset",
        "state.waiting_poll": "waiting",
        "state.waiting_for_app": "waiting for Codex",
        "state.waiting_for_loaded_thread": "waiting for the thread",
        "state.waiting_for_usage": "waiting for usage",
        "state.waiting_retry": "waiting to retry",
        "state.waiting_backoff": "backing off",
        "state.queued": "queued",
        "state.submitting": "submitting",
        "state.resumed": "resumed",
        "state.cancelled": "cancelled",
        "state.superseded": "superseded",
        "state.superseded_by_user": "superseded",
        "state.failed": "failed",
        "state.submission_unknown": "outcome unknown",
        "state.retry_budget_exhausted": "out of attempts",
        "state.no_progress_exhausted": "no progress",
        "state.terminal_failure": "stopped",

        # Public status codes (machine.public_code) and overlays.
        "code.waiting_reset": "waiting for the usage reset",
        "code.waiting_usage": "waiting for usage",
        "code.waiting_thread": "waiting for the conversation",
        "code.scheduled": "retry scheduled",
        "code.failed_retryable": "could not start; retrying",
        "code.submission_claimed": "sending",
        "code.submitted": "sent to Codex",
        "code.withdrawing": "being taken back",
        "code.turn_running": "running in Codex",
        "code.turn_finishing": "finishing",
        "code.recovered": "recovered",
        "code.no_progress": "finished without progress",
        "code.handed_over": "handed over to you",
        "code.recovery_failed": "the recovery turn failed",
        "code.stopped_by_user": "stopped by you",
        "code.outcome_unverified": "outcome not verified",
        "code.delivered_legacy": "delivered (before 0.6)",
        "code.cancelled": "cancelled",
        "code.superseded": "superseded",
        "code.exhausted": "stopped at its limit",
        "code.failed_terminal": "failed",
        "code.submission_unknown": "delivery unknown; not resent",
        "overlay.cancel_pending": "cancel requested",
        "overlay.paused": "paused",
        "overlay.thread_disabled": "off for this conversation",
        "overlay.compatibility_blocked": "Codex version not supported",
        "overlay.engine_unavailable": "watcher not running",
        "overlay.watcher_not_ticking": "watcher not responding",

        # The notification-area icon.
        "tray.title": "Codex Auto Resume",
        "tray.paused": "Paused",
        "tray.idle": "Nothing waiting",
        "tray.waiting": "{n} waiting",
        "tray.running": "{n} running in Codex",
        "tray.next": "next check in {time}",
        "menu.open": "Open Codex Auto Resume",
        "menu.pause": "Pause recovery",
        "menu.resume": "Resume recovery",
        "menu.pending": "Show the {n} waiting",
        "menu.stop": "Stop the watcher",
        "field.show_tray": "Show the icon in the notification area",

        # The Dashboard.
        "nav.overview": "Overview",
        "nav.pending": "Pending",
        "nav.history": "History",
        "nav.statistics": "Statistics",
        "nav.diagnostics": "Diagnostics",
        "nav.settings": "Settings",
        "overview.now": "Right now",
        "overview.waiting": "Waiting",
        "overview.week": "Last 7 days",
        "overview.next": "Next check in {time}",
        "overview.none_waiting": "Nothing is waiting to be recovered",
        "overview.waiting_count": "{n} waiting",
        "overview.running_count": "{n} running in Codex",
        "overview.detected": "Interruptions",
        "overview.sent": "Continuations sent",
        "overview.recovered": "Recovered",
        "overview.success": "Success rate",
        "overview.not_enough": "not enough data yet",
        "overview.last_check": "Last check",
        "overview.engine": "Codex engine",
        "overview.recovery": "Automatic recovery",
        "overview.on": "on",
        "overview.off": "paused",
        "engine.verified": "verified",
        "engine.structurally_compatible": "compatible",
        "engine.incompatible": "not supported",
        "engine.unknown": "unknown",
        "action.refresh": "Refresh",
        "action.retry_now": "Retry now",
        "action.cancel": "Cancel",
        "action.reset_budget": "Give attempts back",
        "action.timeline": "Timeline",
        "action.thread_off": "Turn off for this conversation",
        "action.thread_on": "Turn on for this conversation",
        "action.clear_history": "Clear history",
        "action.export": "Export diagnostics...",
        "action.open_logs": "Open logs folder",
        "action.repair": "Repair installation",
        "action.check_updates": "Check for updates...",
        "action.stop_watcher": "Stop watcher",
        "pending.col_conversation": "Conversation",
        "pending.col_status": "Status",
        "pending.col_category": "Kind",
        "pending.col_next": "Next check",
        "pending.col_attempts": "Attempts",
        "pending.empty": "Nothing is waiting",
        "pending.due": "due now",
        "history.col_outcome": "Outcome",
        "history.col_detected": "Detected",
        "history.col_finished": "Finished",
        "history.empty": "No recoveries yet",
        "confirm.cancel": "Stop recovering \"{name}\"? A continuation already running in Codex is not stopped.",
        "confirm.thread_off": "Turn automatic recovery off for \"{name}\"? Its waiting recoveries are cancelled.",
        "confirm.thread_on": "Turn automatic recovery back on for \"{name}\"? Nothing is sent now; every check still applies.",
        "confirm.reset": "Give \"{name}\" its attempts back? It waits and is checked again; nothing is sent now.",
        "confirm.clear": "Hide finished recoveries from the history? Nothing is deleted, and recoveries that may still change stay visible.",
        "confirm.resume": "Turn automatic recovery back on?",
        "confirm.stop_watcher": "Stop the watcher? It finishes the check it is in and then stops. Nothing waiting is lost, and nothing is recovered until it runs again.",
        "confirm.repair": "Run setup again to repair the Windows registrations, and start the watcher if it is stopped? Settings, pending recoveries, a pause and the sign-in choice are all kept.",
        "confirm.update": "Version {latest} has been published. Download and install it? The archive is checked against its published checksum before anything runs, and your settings, your pause, everything waiting and the sign-in choice are all kept.",
        "stats.period": "Period",
        "stats.days7": "Last 7 days",
        "stats.days30": "Last 30 days",
        "stats.all": "All time",
        "stats.median_wait": "Median wait before sending",
        "stats.median_recovery": "Median time to recover",
        "stats.outcomes": "How recoveries ended",
        "stats.retry_now": "Retry now requests",
        "stats.by_category": "By kind",
        "stats.none": "Nothing yet",
        "diag.watcher": "Watcher",
        "diag.running": "running",
        "diag.not_running": "not running",
        "diag.unknown": "unknown",
        "diag.not_responding": "not responding",
        "diag.version": "Version",
        "diag.engine": "Codex engine",
        "diag.last_check": "Last check",
        "diag.recovery": "Automatic recovery",
        "diag.startup": "Starts at sign-in",
        "diag.update": "Updates",
        "diag.yes": "yes",
        "diag.no": "no",
        "diag.upgrade_pending": "An older watcher still owns the state; finish by restarting the watcher",
        "diag.export_done": "Diagnostics saved. Ids are aliases and paths are removed; read the file before sharing it.",
        "diag.repair_done": "Setup finished.",
        "diag.repair_failed": "Setup did not finish.",
        "diag.repair_running": "Setup is taking longer than usual and is still working. It carries on in the background; look at this page again in a minute.",
        "diag.repair_busy": "An installation or a repair is already running. Try again once it has finished.",
        "diag.repair_incomplete": "Files this installation is made of are missing, so setup could not run. Install it again from the release archive.",
        "diag.update_unasked": "not checked",
        "diag.update_asking": "asking...",
        "diag.update_installing": "installing...",
        "diag.update_current": "up to date",
        "diag.update_available": "v{version} available",
        "diag.update_newer_local": "ahead of v{version}",
        "diag.update_installed": "v{version} installed",
        "diag.update_unavailable": "could not be checked",
        "diag.update_is_current": "Version {version} is the newest published release.",
        "diag.update_is_available": "Version {version} has been published.",
        "diag.update_is_newer_local": "This build is ahead of the newest published release, so there is nothing to install.",
        "diag.update_could_not_ask": "GitHub could not be asked just now. This says nothing about whether an update exists.",
        "diag.update_running": "It is taking longer than usual and is still working. It carries on in the background; look at this page again in a few minutes.",
        "diag.update_incomplete": "Files this installation is made of are missing, so it could not be checked. Install it again from the release archive.",
        "diag.update_failed": "The update check did not finish.",
        "diag.update_done": "Version {version} is installed.",
        "diag.update_watcher_restarted": "The watcher was restarted and is running the new version.",
        "diag.update_watcher_same": "The watcher that is running is still the one from before the update, so it is running the old code. Stop it and start it again from this page.",
        "diag.update_watcher_unknown": "Whether the watcher restarted could not be told.",
        "diag.update_reopen": "Close this window and open it again so it runs the new version.",
        "diag.stop_stopped": "The watcher stopped.",
        "diag.stop_finishing": "The watcher is finishing the check it is in, and stops when that is done.",
        "diag.stop_not_running": "The watcher was not running.",
        "diag.stop_unknown": "Whether the watcher stopped could not be told.",
        "diag.health": "Health",
        "diag.tools": "Tools",
        "timeline.title": "Timeline",
        "timeline.col_time": "Time",
        "timeline.col_event": "Event",
        "timeline.col_detail": "Detail",
        "timeline.empty": "Nothing recorded",
        "event.detected": "Detected",
        "event.state": "Changed",
        "event.claim": "Claimed for sending",
        "event.submitted": "Sent to Codex",
        "event.release_claim": "Claim given back before sending",
        "event.withdraw": "Taken back from Codex's queue",
        "event.release_withdrawn": "Returned to waiting",
        "event.correlated": "Its turn started",
        "event.continuation_after_user_turn": "Ran after your own turn",
        "event.dispatched_despite_delete": "Ran although it was taken back",
        "event.dispatched_while_paused": "Ran although recovery was paused",
        "event.cancel": "Cancelled",
        "event.cancel_requested": "Cancel requested",
        "event.reset_budget": "Attempts given back",
        "event.retry_now": "Retry now",
        "event.identity_drift": "Same turn seen twice; ignored",
        "event.hidden": "Hidden from history",
        "event.migrated": "State upgraded",
        "event.disabled_threads_with_pending": "Conversations switched off with pending work",
        "event.thread_enabled": "Conversation switched back on",
        "event.other": "Other",
        "time.never": "never",
        "time.ago": "{time} ago",
        "time.just_now": "just now",
        "time.seconds": "{n}s",
        "time.minutes": "{n}m",
        "time.hours": "{n}h",
        "time.days": "{n}d",
        "overview.recent": "Recently finished",
        "overview.due": "Due to be checked now",
        "retry.checking": "Checking now. Every safety check still applies; nothing is sent unless they all pass.",
        "retry.next_poll": "The watcher looks at its next check. Every safety check still applies.",
        "retry.later": "The usage reset is later; the watcher checks then.",
        "action.failed": "That could not be done.",
        "pending.unavailable": "This cannot be read right now",
        "history.reset_limit": "Its attempts were already given back as many times as allowed; continue this task in Codex yourself.",

        # Why a request was refused, as the closed set of codes the control layer
        # carries beside its English sentence, so every surface says it in the
        # language the person is reading. The English here is that same sentence;
        # tests/test_locale.py fails if the two ever drift apart.
        "error.already_finished": "that recovery has already finished",
        "error.being_sent": "that recovery is being sent now",
        "error.cancel_requested": "that recovery was cancelled",
        "error.cannot_check_now": "that recovery cannot be checked now",
        "error.cannot_continue": "that recovery cannot be continued",
        "error.file_exists": "That file already exists; choose a new name.",
        "error.in_flight": "that recovery is already in Codex",
        "error.invalid_enabled": "enabled must be true or false",
        "error.invalid_id": "invalid interruption id",
        "error.invalid_thread_id": "thread id must be a canonical UUID",
        "error.newer_state": ("The recovery state was written by a newer version of Codex Auto Resume. Update this installation; do not delete the state."),
        "error.no_such_interruption": "no such interruption",
        "error.not_exhausted": "that recovery has not been exhausted",
        "error.not_installed": "the watcher is not installed here",
        "error.observing": "that recovery is already running in Codex",
        "error.possibly_sent": "that recovery may already have been sent",
        "error.request_failed": "the request could not be completed",
        "error.reset_limit": ("its budget was already reset as many times as allowed; continue this task in Codex yourself"),
        "error.start_failed": "could not start the watcher",
        "error.state_busy": "the state is busy; the cancel was not recorded",
        "error.store_unavailable": "local state is unavailable",
        "error.upgrade_pending": ("Upgrade pending: an older watcher still owns the state. Use Stop watcher, then Start watcher, or sign out and back in."),
        "diag.export_exists": "That file already exists; choose a new name.",
        "settings.load_failed": "Could not read the local settings",
        "settings.saved": "Saved - the watcher uses these from its next check",
        "settings.save_failed": "Could not save.",
        "settings.confirm_restore": "Reset every setting to its recommended value?",
        "settings.restore_failed": "Could not restore defaults.",
    },
    "ko": {
        "group.recovery": "자동 복구",
        "group.limits": "제한",
        "group.notifications": "알림",
        "group.windows": "Windows",

        "field.recover_usage_limit": "사용량 제한",
        "field.recover_network_transient": "네트워크 오류",
        "field.recover_timeout": "시간 초과",
        "field.recover_rate_limit_transient": "일시적 요청 제한",
        "field.recover_server_5xx": "서버 오류",
        "field.recover_stream_interrupted": "스트림 중단",
        "field.notifications": "알림 표시",
        "field.notify_interruption": "중단 감지",
        "field.notify_starting": "복구 시작",
        "field.notify_result": "복구 결과",
        "field.notify_stopped": "중지 또는 시도 소진",
        "field.max_recovery_attempts": "중단당 시도 횟수",
        "field.max_no_progress": "진전 없이 반복되면 중지",
        "field.max_chain_continuations": "작업당 이어서 보내기 횟수",
        "field.retry_timing": "재시도 간격",
        "field.detection_lookback_hours": "확인 범위",
        "field.startup": "Windows 로그인 시 실행",

        "choice.conservative": "여유롭게",
        "choice.normal": "보통",
        "choice.aggressive": "촘촘하게",

        "status.watching": "중단을 감시하는 중",
        "status.not_running": "워처가 실행 중이 아님",
        "status.unknown": "워처 상태를 알 수 없음",
        "status.paused": "감시 일시 중지됨",
        "status.recovery_on": "자동 복구가 켜져 있습니다",
        "status.recovery_paused": "자동 복구가 일시 중지되었습니다",
        "status.recovery_idle": "워처가 실행 중이어야 복구할 수 있습니다",
        "status.pending_none": "대기 중인 작업 없음",
        "status.pending_one": "복구 1건 대기 중",
        "status.pending_many": "복구 {n}건 대기 중",
        "status.unavailable": "상태를 읽을 수 없음",
        "status.unavailable_detail": "설정은 계속 변경하고 저장할 수 있습니다",

        "action.save": "저장",
        "action.close": "닫기",
        "action.restore": "기본값으로",
        "action.start": "워처 시작",
        "action.pause": "자동 복구 일시 정지",
        "action.resume": "자동 복구 다시 켜기",

        "start.working": "워처를 시작하는 중...",
        "start.waiting": "워처가 응답하기를 기다리는 중",
        "start.exited": "시작했다가 곧 종료되었습니다 - 설치 폴더의 로그를 확인하세요",
        "start.unconfirmed": "시작했지만 실행 중인지 아직 확인되지 않았습니다",
        "start.failed": "워처를 시작하지 못했습니다.",

        "panel.pending_title": "재개 대기 중",
        "panel.col_conversation": "대화",
        "panel.col_state": "상태",
        "panel.col_attempts": "시도",
        "panel.more": "외 {n}건",
        "panel.saving": "저장하는 중...",
        "panel.saved": "저장했습니다.",
        "panel.not_saved": "저장하지 못했습니다: {reason}",
        "panel.refused": "거부됨",
        "panel.readonly": "여기서는 읽기 전용입니다. 변경하려면 Codex Auto Resume 설정 창을 사용하세요.",
        "panel.unavailable": "이 화면에서는 설정을 사용할 수 없습니다.",
        "panel.starting": "시작하는 중...",
        "panel.start_failed": "시작하지 못했습니다: {reason}",
        "panel.start_exited": "시작했다가 곧 종료되었습니다. 아무것도 감시하고 있지 않습니다.",
        "panel.start_unconfirmed": "시작했지만 실행 중인지 아직 확인되지 않았습니다. 상태를 다시 확인하세요.",

        "state.waiting_reset": "초기화 대기",
        "state.waiting_poll": "대기 중",
        "state.waiting_for_app": "Codex 대기",
        "state.waiting_for_loaded_thread": "대화 열기 대기",
        "state.waiting_for_usage": "사용량 대기",
        "state.waiting_retry": "재시도 대기",
        "state.waiting_backoff": "백오프 대기",
        "state.queued": "대기열",
        "state.submitting": "전송 중",
        "state.resumed": "재개됨",
        "state.cancelled": "취소됨",
        "state.superseded": "대체됨",
        "state.superseded_by_user": "대체됨",
        "state.failed": "실패",
        "state.submission_unknown": "결과 불명",
        "state.retry_budget_exhausted": "시도 소진",
        "state.no_progress_exhausted": "진전 없음",
        "state.terminal_failure": "중지됨",

        "code.waiting_reset": "사용량 초기화 대기",
        "code.waiting_usage": "사용량 대기",
        "code.waiting_thread": "대화 열기 대기",
        "code.scheduled": "재시도 예약됨",
        "code.failed_retryable": "시작하지 못해 다시 시도",
        "code.submission_claimed": "보내는 중",
        "code.submitted": "Codex에 보냄",
        "code.withdrawing": "되돌리는 중",
        "code.turn_running": "Codex에서 실행 중",
        "code.turn_finishing": "마무리 중",
        "code.recovered": "복구됨",
        "code.no_progress": "진전 없이 끝남",
        "code.handed_over": "사용자에게 넘김",
        "code.recovery_failed": "복구 턴 실패",
        "code.stopped_by_user": "사용자가 중지함",
        "code.outcome_unverified": "결과 확인 안 됨",
        "code.delivered_legacy": "전달됨(0.6 이전)",
        "code.cancelled": "취소됨",
        "code.superseded": "대체됨",
        "code.exhausted": "한도에 도달해 중지",
        "code.failed_terminal": "실패",
        "code.submission_unknown": "전달 여부 불명, 다시 보내지 않음",
        "overlay.cancel_pending": "취소 요청됨",
        "overlay.paused": "일시 정지됨",
        "overlay.thread_disabled": "이 대화는 꺼짐",
        "overlay.compatibility_blocked": "지원되지 않는 Codex 버전",
        "overlay.engine_unavailable": "워처가 실행 중이 아님",
        "overlay.watcher_not_ticking": "워처가 응답하지 않음",

        "tray.title": "Codex Auto Resume",
        "tray.paused": "일시 정지됨",
        "tray.idle": "기다리는 작업 없음",
        "tray.waiting": "{n}개 대기 중",
        "tray.running": "{n}개 Codex에서 실행 중",
        "tray.next": "{time} 뒤 다시 확인",
        "menu.open": "Codex Auto Resume 열기",
        "menu.pause": "자동 복구 일시 정지",
        "menu.resume": "자동 복구 다시 켜기",
        "menu.pending": "기다리는 {n}개 보기",
        "menu.stop": "워처 중지",
        "field.show_tray": "알림 영역에 아이콘 표시",

        "nav.overview": "개요",
        "nav.pending": "대기 중",
        "nav.history": "기록",
        "nav.statistics": "통계",
        "nav.diagnostics": "진단",
        "nav.settings": "설정",
        "overview.now": "지금",
        "overview.waiting": "대기",
        "overview.week": "최근 7일",
        "overview.next": "{time} 뒤 다시 확인",
        "overview.none_waiting": "복구를 기다리는 작업이 없습니다",
        "overview.waiting_count": "{n}개 대기 중",
        "overview.running_count": "{n}개 Codex에서 실행 중",
        "overview.detected": "중단",
        "overview.sent": "보낸 이어서 하기",
        "overview.recovered": "복구됨",
        "overview.success": "성공률",
        "overview.not_enough": "아직 데이터가 부족합니다",
        "overview.last_check": "마지막 확인",
        "overview.engine": "Codex 엔진",
        "overview.recovery": "자동 복구",
        "overview.on": "켜짐",
        "overview.off": "일시 정지됨",
        "engine.verified": "검증됨",
        "engine.structurally_compatible": "호환됨",
        "engine.incompatible": "지원되지 않음",
        "engine.unknown": "알 수 없음",
        "action.refresh": "새로 고침",
        "action.retry_now": "지금 다시 확인",
        "action.cancel": "취소",
        "action.reset_budget": "시도 횟수 되돌리기",
        "action.timeline": "진행 기록",
        "action.thread_off": "이 대화는 끄기",
        "action.thread_on": "이 대화 다시 켜기",
        "action.clear_history": "기록 지우기",
        "action.export": "진단 정보 내보내기...",
        "action.open_logs": "로그 폴더 열기",
        "action.repair": "설치 복구",
        "action.check_updates": "업데이트 확인...",
        "action.stop_watcher": "워처 중지",
        "pending.col_conversation": "대화",
        "pending.col_status": "상태",
        "pending.col_category": "종류",
        "pending.col_next": "다음 확인",
        "pending.col_attempts": "시도",
        "pending.empty": "대기 중인 작업이 없습니다",
        "pending.due": "지금 확인",
        "history.col_outcome": "결과",
        "history.col_detected": "감지",
        "history.col_finished": "종료",
        "history.empty": "아직 복구 기록이 없습니다",
        "confirm.cancel": "\"{name}\"의 복구를 멈출까요? 이미 Codex에서 실행 중인 이어서 하기는 멈추지 않습니다.",
        "confirm.thread_off": "\"{name}\" 대화의 자동 복구를 끌까요? 대기 중인 복구는 취소됩니다.",
        "confirm.thread_on": "\"{name}\" 대화의 자동 복구를 다시 켤까요? 지금 보내지는 않으며, 모든 확인은 그대로 적용됩니다.",
        "confirm.reset": "\"{name}\"의 시도 횟수를 되돌릴까요? 다시 기다렸다가 확인하며, 지금 보내지는 않습니다.",
        "confirm.clear": "끝난 복구를 기록에서 숨길까요? 아무것도 삭제되지 않으며, 아직 바뀔 수 있는 복구는 계속 보입니다.",
        "confirm.resume": "자동 복구를 다시 켤까요?",
        "confirm.stop_watcher": "워처를 중지할까요? 진행 중인 확인만 마치고 멈춥니다. 대기 중인 작업은 사라지지 않으며, 다시 시작할 때까지 복구는 진행되지 않습니다.",
        "confirm.repair": "설정을 다시 실행해 Windows 등록을 고치고, 워처가 멈춰 있으면 다시 시작할까요? 설정, 대기 중인 복구, 일시 정지와 로그인 시 시작 선택은 모두 그대로 유지됩니다.",
        "confirm.update": "{latest} 버전이 나왔습니다. 내려받아 설치할까요? 보관 파일은 실행 전에 공개된 체크섬과 대조하며, 설정과 일시 정지, 대기 중인 항목, 로그인 시 시작 선택은 모두 그대로 둡니다.",
        "stats.period": "기간",
        "stats.days7": "최근 7일",
        "stats.days30": "최근 30일",
        "stats.all": "전체",
        "stats.median_wait": "보내기 전 대기 시간(중앙값)",
        "stats.median_recovery": "복구까지 걸린 시간(중앙값)",
        "stats.outcomes": "복구 결과",
        "stats.retry_now": "지금 다시 확인 요청",
        "stats.by_category": "종류별",
        "stats.none": "아직 없음",
        "diag.watcher": "워처",
        "diag.running": "실행 중",
        "diag.not_running": "실행 중 아님",
        "diag.unknown": "알 수 없음",
        "diag.not_responding": "응답 없음",
        "diag.version": "버전",
        "diag.engine": "Codex 엔진",
        "diag.last_check": "마지막 확인",
        "diag.recovery": "자동 복구",
        "diag.startup": "로그인 시 시작",
        "diag.update": "업데이트",
        "diag.yes": "예",
        "diag.no": "아니요",
        "diag.upgrade_pending": "이전 버전 워처가 아직 상태를 쓰고 있습니다. 워처를 다시 시작하면 끝납니다",
        "diag.export_done": "진단 정보를 저장했습니다. ID는 별칭으로 바뀌고 경로는 지워졌습니다. 공유하기 전에 파일을 읽어 보세요.",
        "diag.repair_done": "설정을 마쳤습니다.",
        "diag.repair_failed": "설정을 끝내지 못했습니다.",
        "diag.repair_running": "설정이 평소보다 오래 걸리고 있으며 아직 진행 중입니다. 백그라운드에서 계속되니 잠시 뒤 이 페이지를 다시 보세요.",
        "diag.repair_busy": "설치나 복구가 이미 실행 중입니다. 끝난 뒤에 다시 시도하세요.",
        "diag.repair_incomplete": "이 설치를 이루는 파일이 없어서 설정을 실행할 수 없습니다. 릴리스 압축 파일로 다시 설치하세요.",
        "diag.update_unasked": "확인하지 않음",
        "diag.update_asking": "묻는 중...",
        "diag.update_installing": "설치하는 중...",
        "diag.update_current": "최신",
        "diag.update_available": "v{version} 나옴",
        "diag.update_newer_local": "v{version}보다 앞섬",
        "diag.update_installed": "v{version} 설치함",
        "diag.update_unavailable": "확인하지 못함",
        "diag.update_is_current": "{version} 버전이 가장 최근에 발행된 릴리스입니다.",
        "diag.update_is_available": "{version} 버전이 발행되었습니다.",
        "diag.update_is_newer_local": "이 빌드가 가장 최근 발행본보다 앞서 있어 설치할 것이 없습니다.",
        "diag.update_could_not_ask": "지금은 GitHub에 물어보지 못했습니다. 업데이트가 있는지 없는지는 알 수 없습니다.",
        "diag.update_running": "평소보다 오래 걸리고 있으며 아직 진행 중입니다. 배경에서 계속되니 몇 분 뒤에 이 쪽을 다시 보세요.",
        "diag.update_incomplete": "이 설치를 이루는 파일이 없어 확인하지 못했습니다. 릴리스 보관 파일로 다시 설치하세요.",
        "diag.update_failed": "업데이트 확인을 끝내지 못했습니다.",
        "diag.update_done": "{version} 버전을 설치했습니다.",
        "diag.update_watcher_restarted": "워처를 다시 시작했고 새 버전으로 돌고 있습니다.",
        "diag.update_watcher_same": "지금 도는 워처가 업데이트 전의 그 워처라서 예전 코드로 돌고 있습니다. 이 쪽에서 멈췄다가 다시 시작하세요.",
        "diag.update_watcher_unknown": "워처가 다시 시작했는지는 알 수 없었습니다.",
        "diag.update_reopen": "이 창을 닫았다가 다시 열면 새 버전으로 실행됩니다.",
        "diag.stop_stopped": "워처가 중지되었습니다.",
        "diag.stop_finishing": "워처가 진행 중인 확인을 마치는 중이며, 끝나면 중지됩니다.",
        "diag.stop_not_running": "워처가 실행 중이 아니었습니다.",
        "diag.stop_unknown": "워처가 중지되었는지 확인할 수 없었습니다.",
        "diag.health": "상태",
        "diag.tools": "도구",
        "timeline.title": "진행 기록",
        "timeline.col_time": "시각",
        "timeline.col_event": "일",
        "timeline.col_detail": "자세히",
        "timeline.empty": "기록된 것이 없습니다",
        "event.detected": "감지됨",
        "event.state": "바뀜",
        "event.claim": "보내려고 예약함",
        "event.submitted": "Codex에 보냄",
        "event.release_claim": "보내기 전에 예약을 되돌림",
        "event.withdraw": "Codex 대기열에서 되돌림",
        "event.release_withdrawn": "다시 대기로 돌아감",
        "event.correlated": "턴이 시작됨",
        "event.continuation_after_user_turn": "사용자의 턴 뒤에 실행됨",
        "event.dispatched_despite_delete": "되돌렸지만 실행됨",
        "event.dispatched_while_paused": "일시 정지 중이었지만 실행됨",
        "event.cancel": "취소됨",
        "event.cancel_requested": "취소 요청됨",
        "event.reset_budget": "시도 횟수 되돌림",
        "event.retry_now": "지금 다시 확인",
        "event.identity_drift": "같은 턴을 두 번 봄; 무시함",
        "event.hidden": "기록에서 숨김",
        "event.migrated": "상태를 업그레이드함",
        "event.disabled_threads_with_pending": "대기 중인 작업이 있는 대화가 꺼져 있음",
        "event.thread_enabled": "대화를 다시 켬",
        "event.other": "기타",
        "time.never": "없음",
        "time.ago": "{time} 전",
        "time.just_now": "방금",
        "time.seconds": "{n}초",
        "time.minutes": "{n}분",
        "time.hours": "{n}시간",
        "time.days": "{n}일",
        "overview.recent": "최근에 끝난 복구",
        "overview.due": "지금 확인할 차례",
        "retry.checking": "지금 확인합니다. 모든 안전 확인은 그대로 적용되며, 전부 통과해야만 보냅니다.",
        "retry.next_poll": "워처가 다음 확인 때 살펴봅니다. 모든 안전 확인은 그대로 적용됩니다.",
        "retry.later": "사용량 초기화가 더 뒤라서 그때 확인합니다.",
        "action.failed": "그 작업을 하지 못했습니다.",
        "pending.unavailable": "지금은 읽을 수 없습니다",
        "history.reset_limit": "시도 횟수를 되돌릴 수 있는 만큼 이미 되돌렸습니다. 이 작업은 Codex에서 직접 이어서 하세요.",

        "error.already_finished": "이미 끝난 복구입니다.",
        "error.being_sent": "지금 보내는 중인 복구입니다.",
        "error.cancel_requested": "취소한 복구입니다.",
        "error.cannot_check_now": "이 복구는 지금 다시 확인할 수 없습니다.",
        "error.cannot_continue": "이 복구는 이어서 할 수 없습니다.",
        "error.file_exists": "이미 있는 파일입니다. 새 이름을 고르세요.",
        "error.in_flight": "이미 Codex에 넘어간 복구입니다.",
        "error.invalid_enabled": "켜짐 또는 꺼짐 값이어야 합니다.",
        "error.invalid_id": "복구 ID가 올바르지 않습니다.",
        "error.invalid_thread_id": "대화 ID가 올바르지 않습니다.",
        "error.newer_state": ("복구 상태를 더 새로운 버전의 Codex Auto Resume이 썼습니다. 이 설치를 업데이트하세요. 상태를 지우지는 마세요."),
        "error.no_such_interruption": "해당 복구를 찾을 수 없습니다.",
        "error.not_exhausted": "아직 시도 횟수를 다 쓰지 않은 복구입니다.",
        "error.not_installed": "여기에는 워처가 설치되어 있지 않습니다.",
        "error.observing": "이미 Codex에서 실행 중인 복구입니다.",
        "error.possibly_sent": "이미 보냈을 수 있는 복구입니다.",
        "error.request_failed": "요청을 처리하지 못했습니다.",
        "error.reset_limit": "시도 횟수를 되돌릴 수 있는 만큼 이미 되돌렸습니다. 이 작업은 Codex에서 직접 이어서 하세요.",
        "error.start_failed": "워처를 시작하지 못했습니다.",
        "error.state_busy": "상태가 사용 중이라 취소를 기록하지 못했습니다.",
        "error.store_unavailable": "복구 상태를 읽을 수 없습니다.",
        "error.upgrade_pending": ("이전 버전 워처가 아직 상태를 쓰고 있습니다. \"워처 중지\" 뒤에 \"워처 시작\"을 누르거나, 로그아웃했다가 다시 로그인하세요."),
        "diag.export_exists": "이미 있는 파일입니다. 새 이름을 고르세요.",
        "settings.load_failed": "로컬 설정을 읽지 못했습니다",
        "settings.saved": "저장했습니다. 워처가 다음 확인부터 이 설정을 씁니다",
        "settings.save_failed": "저장하지 못했습니다.",
        "settings.confirm_restore": "모든 설정을 권장값으로 되돌릴까요?",
        "settings.restore_failed": "기본값으로 되돌리지 못했습니다.",
    },
}


def catalog(environ=None) -> dict:
    """The strings for the language this machine resolves to, as a plain dict.

    Handed whole to each surface rather than looked up key by key across a process
    boundary: the standalone window makes one bridge call at startup and the panel is
    seeded once, so neither can end up rendering half of one language.
    """
    return dict(STRINGS[messages.language(environ)])


def language(environ=None) -> str:
    return messages.language(environ)
