// Generated by build/make_brand.py from src/codex_auto_resume/brand.py.
// Do not edit: tests/test_brand.py regenerates this file and compares it.
//
// The window is light-only. Windows Forms has no theme story worth the complexity here,
// and a settings window that guessed at dark mode and got it half right would look worse
// than one that is honestly light. The dark half of the palette exists for the Codex
// panel, which does follow the host.

using System.Drawing;

namespace CodexAutoResume
{
    internal static class Brand
    {
        internal static readonly Color Ink      = Color.FromArgb(0x0F, 0x1B, 0x2D);  // #0F1B2D, text
        internal static readonly Color Muted    = Color.FromArgb(0x5A, 0x6B, 0x7F);  // #5A6B7F, secondary text
        internal static readonly Color Line     = Color.FromArgb(0xDC, 0xE3, 0xEC);  // #DCE3EC, hairlines and card edges
        internal static readonly Color Surface  = Color.FromArgb(0xFF, 0xFF, 0xFF);  // #FFFFFF, cards
        internal static readonly Color Canvas   = Color.FromArgb(0xF2, 0xF5, 0xF9);  // #F2F5F9, the window behind them
        internal static readonly Color Accent   = Color.FromArgb(0x12, 0x57, 0xB8);  // #1257B8, anything to read or to click
        internal static readonly Color OnAccent = Color.FromArgb(0xFF, 0xFF, 0xFF);  // #FFFFFF, text drawn on the accent
        internal static readonly Color Active   = Color.FromArgb(0x06, 0xB6, 0xD4);  // #06B6D4, fill only: running
        internal static readonly Color Idle     = Color.FromArgb(0x94, 0xA3, 0xB8);  // #94A3B8, fill only: stopped

        internal const string HexAccent = "#1257B8";
        internal const string HexBrand = "#1257B8";
    }
}
